default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-mister-cocktail_development

test:
  <<: *default
  database: rails-mister-cocktail_test

production:
  <<: *default
  database: rails-mister-cocktail_production
  # username: giftapes
  # password: <%= ENV['GIFTAPES_DATABASE_PASSWORD'] %>