COCKTAILS = {
  'aperol spritz': { 'vodka': '30ml', 'lime juice': '15ml', 'ginger beer': '90ml', 'lime': '1 wedge' },
  # 'asian hooker': ,
  # 'bay breeze':,
  # 'bloody mary':,
  # 'cosmopolitan':,
  'daiquiri': { 'light rum': '60ml', 'sugar syrup': '30ml', 'lime juice': '22.5ml', 'lime': '1 wheel' },
  # # 'espresso martini': ,
  # # 'jaegerbomb': ,
  # # 'manhattan': ,
  'margarita': { 'tequila': '60ml', 'lime juice': '1 whole', 'triple sec': '15ml', 'lime': '1 wedge' },
  # # 'michelada': ,
  # # 'mojito': ,
  # # 'moscow mule': ,
  # # 'old fashioned': ,
  # # 'penicillin': ,
  'pina colada': { 'rum': '60ml', 'pineapple juice': '60ml', 'coconut cream': '60ml', 'ice': '1.5 cups' },
  # # 'sangria': ,
  # # 'sex on the beach': ,
  # 'whiskey sour':
}
