COCKTAILS = [
  { name: 'aperol spritz',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095595/miss-cocktail/aperol.jpg',
    ingredients: { 'vodka': '30ml', 'lime juice': '15ml', 'ginger beer': '90ml', 'lime': '1 wedge' }},
  { name: 'bay breeze',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095587/miss-cocktail/bay%20breeze.jpg',
    ingredients: { 'vodka': '60ml', 'cranberry juice': '90ml', 'pineapple juice': '90ml', 'lime': '1 wedge' }},
  { name: 'black russian',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608098035/miss-cocktail/black-russian.jpg',
    ingredients: { 'vodka': '30ml', 'kahlua': '30ml', 'cherry': '1 whole (garnish)' }},
  { name: 'bloody mary',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608096977/miss-cocktail/bloody-mary.jpg',
    ingredients: { 'vodka': '60ml', 'tomato juice': '120ml', 'tabasco': '2 dashes', 'worcestershire sauce': '2 dashes', 'lime': '1 wedge', 'lemon': '1 wedge', 'horseradish': '2 tsp' }},
  { name: 'cosmopolitan',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095594/miss-cocktail/cosmo.jpg',
    ingredients: { 'vodka': '45ml', 'cointreau': '30ml', 'lime juice': '15ml', 'cranberry juice': '1 dash', 'lime': '1 wedge' }},
  { name: 'daiquiri',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095572/miss-cocktail/daiquiri.jpg',
    ingredients: { 'light rum': '60ml', 'sugar syrup': '30ml', 'lime juice': '22.5ml', 'lime': '1 wheel' }},
  { name: 'espresso martini',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095592/miss-cocktail/espresso.jpg',
    ingredients: { 'vodka': '40ml', 'kahlua': '20ml', 'espresso': '20ml', 'coffee beans': '3 whole beans (garnish)' }},
  { name: 'long island iced tea',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095578/miss-cocktail/iced-tea.jpg',
    ingredients: { 'vodka': '20ml', 'light rum': '20ml', 'gin': '20ml', 'tequila': '20ml', 'triple sec': '20ml', 'lemon juice': '40ml', 'cola': '20ml', 'lime': '1 wheel' }},
  { name: 'manhattan',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095573/miss-cocktail/manhattan.jpg',
    ingredients: { 'bourbon': '60ml', 'sweet vermouth': '30ml', 'bitters': '2 dashes', 'orange bitters': '1 dash', 'brandied cherry': 'garnish' }},
  { name: 'margarita',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095599/miss-cocktail/margartia.jpg',
    ingredients: { 'tequila': '60ml', 'lime juice': '1 whole', 'triple sec': '15ml', 'lime': '1 wedge' }},
  { name: 'michelada',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608098360/miss-cocktail/michelada.jpg',
    ingredients: { 'tomato juice': '150ml', 'worcestershire sauce': '4 drops', 'soy sauce': '4 drops', 'hot sauce': '4 drops', 'lager': '375ml', 'lime juice': '60ml', 'lime': 'wedges', 'tajin seasoning': '3/4 tsp', 'kosher salt': '2 tbsp', 'ice': 'to serve' }},
  { name: 'mojito',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608097089/miss-cocktail/mojito.jpg',
    ingredients: { 'mint leaves': '10 fresh leaves', 'white sugar': '2 tbsp', 'white rum': '45ml', 'club soda': '125ml', 'lime': '1/2, cut into wedges' }},
  { name: 'moscow mule',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095596/miss-cocktail/moscow-mule.jpg',
    ingredients: { 'tequila': '60ml', 'lime juice': '1 whole', 'triple sec': '15ml', 'lime': '1 wedge' }},
  { name: 'negroni',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095578/miss-cocktail/negroni.jpg',
    ingredients: { 'gin': '20ml', 'campari': '20ml', 'sweet vermouth': '20ml', 'orange zest': 'granish' }},
  { name: 'old fashioned',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095573/miss-cocktail/old-fashioned.jpg',
    ingredients: { 'bourbon': '60ml', 'sugar': '1/2 tsp', 'bitters': '3 dashes', 'water': '1 tsp', 'orange peel': 'garnish' }},
  { name: 'penicillin',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095567/miss-cocktail/penicillin.jpg',
    ingredients: { 'blended scotch': '60ml', 'single malt scotch': '7.5ml', 'lemon juice': '22.5ml', 'honey-ginger syrup': '22.5ml', 'candied ginger': 'garnish' }},
  { name: 'pina colada',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095604/miss-cocktail/pina-colada.jpg',
    ingredients: { 'rum': '60ml', 'pineapple juice': '60ml', 'coconut cream': '60ml', 'ice': '1.5 cups' }},
  { name: 'sangria',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608095577/miss-cocktail/sangria.jpg',
    ingredients: { 'apple': '1/4 sliced', 'orange': '1/4 sliced', 'brown sugar': '1 tbsp', 'orange juice': '90ml', 'brandy': '40ml', 'red wine': '375ml', 'ice': '100g' }},
  { name: 'sex on the beach',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608100319/miss-cocktail/sex-drink.jpg',
    ingredients: { 'vodka': '60ml', 'peach schnapps': '30ml', 'grapefruit juice': '60ml', 'cranberry juice': '60ml', 'lemon juice': '1 tsp (optional)' }},
  { name: 'whiskey sour',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608098444/miss-cocktail/whiskey-sour.jpg',
    ingredients: { 'bourbon': '60ml', 'simple syrup': '15ml', 'lemon juice': '22.5ml', 'egg white': '15ml', 'bitters': 'garnish' }},
  { name: 'white russian',
    photo: 'https://res.cloudinary.com/susanjsp/image/upload/v1608098636/miss-cocktail/white-russian.jpg',
    ingredients: { 'vodka': '40ml', 'kahlua': '40ml', 'cream': '40ml' }}
]
