cocktails = [
  { 'Name': 'Aperol Spritz', 'Vodka': '30ml', 'Lime Juice': '15ml', 'Ginger Beer': '90ml', 'Lime': '1 wedge' },
  'Asian Hooker': ,
  'Bay Breeze':,
  'Bloody Mary':,
  'Cosmopolitan':,
  'Daiquiri':,
  'Espresso Martini': ,
  'Jaegerbomb': ,
  'Manhattan': ,
  'Margarita': ,
  'Michelada': ,
  'Mojito': ,
  'Moscow Mule': ,
  'Old Fashioned': ,
  'Penicillin': ,
  'Pina Colada': ,
  'Sex on the beach': ,
  'Whiskey Sour': ,
]
